# Generated by Django 3.2.9 on 2022-02-05 10:12

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ampara_Declared_forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('con_status', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_Disrict_boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_n', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_DS_boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsd_n', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_Forest_cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest_cover_id', models.IntegerField(blank=True, null=True)),
                ('lc', models.CharField(blank=True, max_length=25, null=True)),
                ('forest_typ', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_GN_boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnd_n', models.CharField(blank=True, max_length=254, null=True)),
                ('gnd_no', models.CharField(blank=True, max_length=254, null=True)),
                ('district_n', models.CharField(blank=True, max_length=254, null=True)),
                ('dsd_n', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_Landuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcode', models.CharField(blank=True, max_length=50, null=True)),
                ('scode', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('main_land', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_Major_irr_tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('map_id', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_Other_state_forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid_fc_201', models.BigIntegerField(blank=True, null=True)),
                ('forest_typ', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_PA_Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('con_status', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('owner', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_River_basin_boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rb_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('basin_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_River_stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl_nm_tran', models.CharField(blank=True, max_length=50, null=True)),
                ('road_class', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.CharField(blank=True, max_length=70, null=True)),
                ('end', models.CharField(blank=True, max_length=70, null=True)),
                ('tot_length', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_Slope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope_id', models.BigIntegerField(blank=True, null=True)),
                ('gridcode', models.BigIntegerField(blank=True, null=True)),
                ('sl_class', models.CharField(blank=True, max_length=15, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ampara_Small_irr_tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('map_id', models.BigIntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=254, null=True)),
                ('asc_field', models.CharField(blank=True, max_length=254, null=True)),
                ('gnd', models.CharField(blank=True, max_length=254, null=True)),
                ('river_b_na', models.CharField(blank=True, max_length=25, null=True)),
                ('dsd', models.CharField(blank=True, max_length=37, null=True)),
                ('ownership', models.CharField(blank=True, max_length=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_Declared_forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('con_status', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_District_boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField(blank=True, null=True)),
                ('district_n', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_DS_boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsd_n', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_Forest_cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('area_final', models.FloatField(blank=True, null=True)),
                ('f_type', models.CharField(blank=True, max_length=25, null=True)),
                ('lc', models.CharField(blank=True, max_length=25, null=True)),
                ('forest_typ', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_GN_boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnd_n', models.CharField(blank=True, max_length=254, null=True)),
                ('gnd_no', models.CharField(blank=True, max_length=254, null=True)),
                ('district_n', models.CharField(blank=True, max_length=254, null=True)),
                ('dsd_n', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_Landuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcode', models.CharField(blank=True, max_length=50, null=True)),
                ('scode', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('main_land', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_Major_irr_tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('map_id', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_Other_state_forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest_typ', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_PA_cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('con_status', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_River_basin_boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rb_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('basin_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_River_stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl_nm_tran', models.CharField(blank=True, max_length=50, null=True)),
                ('road_class', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.CharField(blank=True, max_length=70, null=True)),
                ('end', models.CharField(blank=True, max_length=70, null=True)),
                ('start_km_p', models.FloatField(blank=True, null=True)),
                ('end_km_pos', models.FloatField(blank=True, null=True)),
                ('tot_length', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_Slope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope_id', models.BigIntegerField(blank=True, null=True)),
                ('gridcode', models.BigIntegerField(blank=True, null=True)),
                ('sl_class', models.CharField(blank=True, max_length=15, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mannar_Small_irr_tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('map_id', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ShapeLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shape Layer')),
                ('file', models.FileField(blank=True, upload_to='%y%m%d')),
                ('uploaded_date', models.DateField(default=datetime.date.today)),
                ('layerof', models.IntegerField(choices=[(1, 'Mannar_District_boundary'), (2, 'Mannar_DS_boundary'), (3, 'Mannar_GN_boundary'), (4, 'Mannar_Declared_forest'), (5, 'Mannar_Forest_cover'), (6, 'Mannar_Landuse'), (7, 'Mannar_Major_irr_tank'), (8, 'Mannar_Other_state_forest'), (9, 'Mannar_PA_cover'), (10, 'Mannar_Place'), (11, 'Mannar_River_basin_boundary'), (12, 'Mannar_River_stream'), (13, 'Mannar_Road'), (14, 'Mannar_Slope'), (15, 'Mannar_Small_irr_tank'), (16, 'Ampara_Declared_forest'), (17, 'Ampara_Disrict_boundary'), (18, 'Ampara_DS_boundary'), (19, 'Ampara_Forest_cover'), (20, 'Ampara_GN_boundary'), (21, 'Ampara_Landuse'), (22, 'Ampara_Major_irr_tank'), (23, 'Ampara_Other_state_forest'), (24, 'Ampara_Place'), (25, 'Ampara_River_basin_boundary'), (26, 'Ampara_River_stream'), (27, 'Ampara_Road'), (28, 'Ampara_Slope'), (29, 'Ampara_Small_irr_tank'), (30, 'Ampara_PA_Cover')], default=1)),
                ('table_name', models.CharField(blank=True, max_length=255, verbose_name='Table name')),
            ],
        ),
    ]
