# Generated by Django 3.2.9 on 2022-02-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampara_pa_cover',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ampara_pa_cover',
            name='con_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ampara_pa_cover',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ampara_pa_cover',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
