# Generated by Django 3.2.9 on 2022-01-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_auto_20220113_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='District name')),
            ],
        ),
        migrations.DeleteModel(
            name='Layers',
        ),
        migrations.DeleteModel(
            name='MannarDistrictBoundary',
        ),
    ]
