# Generated by Django 3.2.9 on 2022-07-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_auto_20220702_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProtectedArea',
        ),
    ]
