# Generated by Django 3.2.9 on 2022-01-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_mannardsboundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapelayers',
            name='table_name',
            field=models.CharField(default='a', max_length=255, verbose_name='District name'),
            preserve_default=False,
        ),
    ]
