# Generated by Django 3.2.9 on 2022-01-15 07:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_mannarforestcover_mannargnboundary_mannarirrigationtank_mannarlanduse_mannarnationalroadnetwork_mann'),
    ]

    operations = [
        migrations.CreateModel(
            name='MannarSmallIrrigationTankPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('river_b_na', models.CharField(max_length=256, verbose_name='River B Na')),
                ('ownership', models.CharField(max_length=256, verbose_name='Ownership')),
                ('functional', models.CharField(max_length=256, verbose_name='Functional')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MannarSmallIrrigationTankPoly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('river_b_na', models.CharField(max_length=256, verbose_name='River B Na')),
                ('ownership', models.CharField(max_length=256, verbose_name='Ownership')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='MannarSmallIrrigationTank',
        ),
        migrations.AlterField(
            model_name='shapelayers',
            name='layerof',
            field=models.IntegerField(choices=[(1, 'Mannar District boundary'), (2, 'Mannar DS Boundary'), (3, 'Mannar GN boundary'), (4, 'Mannar Forestcover'), (5, 'Mannar irrigation tank'), (6, 'Mannar Landuse'), (7, 'Mannar Roads'), (8, 'Mannar PACover'), (9, 'Mannar Places'), (10, 'Mannar Remaining Forest'), (11, 'Mannar River basin'), (12, 'Mannar Small Irrigation Tanks Point'), (13, 'Mannar Small Irrigation Tanks Polygon')], default=1),
        ),
    ]
