# Generated by Django 3.2.9 on 2022-01-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0010_auto_20220115_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannargnboundary',
            name='num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GND Number'),
        ),
        migrations.AlterField(
            model_name='mannarlanduse',
            name='main_category',
            field=models.IntegerField(blank=True, null=True, verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='mannarlanduse',
            name='mcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='MCode'),
        ),
        migrations.AlterField(
            model_name='mannarlanduse',
            name='scode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SCode'),
        ),
        migrations.AlterField(
            model_name='mannarlanduse',
            name='sub_category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='mannarlanduse',
            name='year_of_update',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='mannarnationalroadnetwork',
            name='ends_at',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ends At'),
        ),
        migrations.AlterField(
            model_name='mannarnationalroadnetwork',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Road Name'),
        ),
        migrations.AlterField(
            model_name='mannarnationalroadnetwork',
            name='road_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Road Class'),
        ),
        migrations.AlterField(
            model_name='mannarnationalroadnetwork',
            name='road_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Road Type'),
        ),
        migrations.AlterField(
            model_name='mannarnationalroadnetwork',
            name='starts_at',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Starts At'),
        ),
        migrations.AlterField(
            model_name='mannarpacover',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='mannarpacover',
            name='con_status',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Con Status'),
        ),
        migrations.AlterField(
            model_name='mannarpacover',
            name='date_of_gaz',
            field=models.DateField(blank=True, null=True, verbose_name='Date of gaz'),
        ),
        migrations.AlterField(
            model_name='mannarpacover',
            name='gaz_no',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='GAZ Num'),
        ),
        migrations.AlterField(
            model_name='mannarpacover',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mannarpacover',
            name='owner',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='mannarpacover',
            name='remarke',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='mannarriverbasin',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoint',
            name='functional',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Functional'),
        ),
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoint',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoint',
            name='ownership',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ownership'),
        ),
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoint',
            name='river_b_na',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='River B Na'),
        ),
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoly',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoly',
            name='ownership',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ownership'),
        ),
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoly',
            name='river_b_na',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='River B Na'),
        ),
        migrations.AlterField(
            model_name='mannarstreamnetwork',
            name='from_node',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannarstreamnetwork',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mannarstreamnetwork',
            name='to_node',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shapelayers',
            name='layerof',
            field=models.IntegerField(choices=[(1, 'Mannar District boundary'), (2, 'Mannar DS Boundary'), (3, 'Mannar GN boundary'), (4, 'Mannar Forestcover'), (5, 'Mannar irrigation tank'), (6, 'Mannar Landuse'), (7, 'Mannar Roads'), (8, 'Mannar PACover'), (9, 'Mannar Places'), (10, 'Mannar Remaining Forest'), (11, 'Mannar River basin'), (12, 'Mannar Small Irrigation Tanks Point'), (13, 'Mannar Small Irrigation Tanks Polygon'), (14, 'Mannar Stream Network')], default=1),
        ),
    ]
