# Generated by Django 3.2.9 on 2022-01-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0011_auto_20220115_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannarpacover',
            name='date_of_gaz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Date of gaz'),
        ),
    ]
