# Generated by Django 3.2.9 on 2022-01-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0012_alter_mannarpacover_date_of_gaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannarpacover',
            name='name',
            field=models.CharField(default='1', max_length=256, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mannarriverbasin',
            name='name',
            field=models.CharField(default='1', max_length=256, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoint',
            name='name',
            field=models.CharField(default=' ', max_length=256, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoly',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mannarstreamnetwork',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
