# Generated by Django 3.2.9 on 2022-01-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0014_auto_20220115_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannarsmallirrigationtankpoint',
            name='remarke',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Remarks'),
        ),
    ]
