# Generated by Django 3.2.9 on 2022-01-15 12:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0015_mannarsmallirrigationtankpoint_remarke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannarsmallirrigationtankpoint',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
