# Generated by Django 3.2.9 on 2022-01-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0016_alter_mannarsmallirrigationtankpoint_geom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MannarStreamNetwork',
        ),
    ]
