# Generated by Django 3.2.9 on 2022-01-15 13:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0017_delete_mannarstreamnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='MannarStreamNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('from_node', models.IntegerField(blank=True, null=True)),
                ('to_node', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
