# Generated by Django 3.2.9 on 2021-12-05 10:29

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Layer Name')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Layer description')),
                ('file', models.FileField(blank=True, upload_to='%y%m%d')),
                ('uploaded_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Layers',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senris.district')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senris.incidenttype')),
            ],
        ),
    ]
