# Generated by Django 3.2.9 on 2022-02-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Entity type')),
            ],
        ),
        migrations.CreateModel(
            name='SensitiveEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senris.entitytype')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='senris.sensitiveentity'),
        ),
    ]
