# Generated by Django 3.2.9 on 2022-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='admin_area',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='admun'),
        ),
    ]
