# Generated by Django 3.2.9 on 2022-02-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0002_auto_20220215_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensitiveentity',
            name='entity_type',
        ),
        migrations.DeleteModel(
            name='EntityType',
        ),
    ]
