# Generated by Django 3.2.9 on 2022-03-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0003_rename_admin_area_incident_gnd_dsd'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitiveentity',
            name='color_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Hex color code'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='gnd_dsd',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='gnd_dsd'),
        ),
    ]
