# Generated by Django 3.2.9 on 2022-03-31 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0004_auto_20220331_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='damage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='senris.damage'),
        ),
    ]
