# Generated by Django 3.2.9 on 2022-03-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0005_alter_incident_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='senris.sensitiveentity'),
        ),
    ]
