# Generated by Django 3.2.9 on 2022-04-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0007_auto_20220407_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='collected_location',
        ),
    ]
