# Generated by Django 3.2.9 on 2022-04-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0008_remove_incident_collected_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='reporter',
        ),
    ]
