# Generated by Django 3.2.9 on 2022-04-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0009_remove_incident_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='modified_at',
        ),
    ]
