# Generated by Django 3.2.9 on 2022-04-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0011_auto_20220410_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
