# Generated by Django 3.2.9 on 2022-06-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senris', '0012_incident_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='contact',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Contact No'),
        ),
    ]
